---
- name: Chequear los espacios en disco de las maquinas
  hosts: all
  gather_facts: false
  vars:
    disksize: 7
    disk: C

  tasks:
    - name: "Comprobar espacio libre en {{ disk }}:"
      win_shell: "write-host ([math]::Round((Get-PSDrive {{ disk }} | Select-Object Free).free / 1024 / 1024 / 1024,2))"
      register: freespace

    - name: informe de espacio libre en disco
      debug:
        msg: "El espacio disponible del discpo {{ disk }}: es {{ freespace.stdout }} GB"


    - name: "Fallar si no hay espacio suficiente"
      fail:
        msg: "La maquina {{inventory_hostname}} tiene menos de {{ disksize }} GB disponibles"
      when: "freespace.stdout | int is lt disksize"
