---
- hosts: all
  gather_facts: yes
  tasks:
  - name: Información sobre discos
    win_disk_facts:

  - name: Convierte el primer disco del sistema a varios formatos
    debug:
      msg: "El tamaño total del disco C: es {{ disksize_gib }}"
    vars:
      disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'
              # Mostrar el tamaño del disco en Gibibytes
      disksize_gib: '{{ (disk.size/1024|pow(3))|round|int }} GiB'
