---
- name: Instalar sólo determinadas actualizaciones en función de los números de KB
  hosts: all
  tasks:
   - name: Crear Directorio
     ansible.windows.win_file:
       path: c:\temp
       state: directory

   - debug:
       msg: "Crear directorio para los archivos de log"

   - name: Instalar sólo determinadas actualizaciones en función de los números de KB
     ansible.windows.win_updates:
       category_names: '*'
       accept_list:
        - "{{ KB }}"
       log_path: c:\temp\patching.txt
     register: update_result
     until: update_result.found_update_count == 0

   - debug:
       msg: 'Logfile in c:\temp\patching.txt'
