- name: Revision de parches en windows server
  hosts: all
  tasks:
    - name: Comprobar si faltan actualizaciones
      ansible.windows.win_updates:
        category_names:
          - Application
          - Connectors
          - CriticalUpdates
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - SecurityUpdates
          - ServicePacks
          - Tools
          - UpdateRollups
          - Updates
        state: searched
        log_path: C:\Windows\Temp\Pre-AllUpdatesFound.txt
      register: update_results

#    - name: Informe de resultados actualizados
#      debug:
#        var: update_results


    - name: Informe de resultados actualizados
      ansible.builtin.debug:
        msg: |
          {% for k in update_results.updates %}
          {{ update_results.updates[k].title }}
          {% endfor %}

    - name: Informe de Categorias encontradas
      ansible.builtin.debug:
        msg: |
          {% for k in update_results.updates %}
          {{ update_results.updates[k].categories }}
          {% endfor %}
