---
- name: Windows Users
  vars:
    grupo: LocalGroup
  hosts: all

  tasks:
    - name: Crear grupo local el cual contendra los nuevos usuarios
      ansible.windows.win_group:
        name: LocalGroup
        description: Allow access to C:\Development folder

    - name:  Crear usuario local
      ansible.windows.win_user:
        name: '{{ item.name }}'
        password: '{{ item.password }}'
        groups: "{{ grupo }}"
        update_password: on_create
        password_never_expires: yes
      loop:
      - name: ansible01
        password: Password123.

    - name: Crear carpeta C:\Development
      ansible.windows.win_file:
        path: C:\Development
        state: directory
