---
- name: Verificar e instalar un paquete en Linux
  hosts: all
  vars:
    paquete: telnet
  gather_facts: no
  tasks:

  - name: Verificar si el paquete est치 instalado
    ansible.builtin.package:
      name: "{{ paquete }}""
      state: present
    register: package_status

  - name: Instalar el paquete si no est치 instalado
    ansible.builtin.package:
      name: "{{ paquete }}"
      state: present
    when: not package_status.changed

  - name: Mostrar resultado
    debug:
      msg: "El paquete {{ nombre_del_paquete }} est치 instalado o se instal칩 correctamente."
    when: package_status.changed or package_status.failed
