---
- name: Validar si un archivo de configuracion existe
  hosts: all

  tasks:
  - name: Validar si el archivo de config exite
    stat:
      path: "{{ path }}"
    register: register_name

  - name: Registrar si el archivo existe
    debug:
      msg: "El archivo o directorio existe"
    when: register_name.stat.exists
